$ANSIBLE_VAULT;1.1;AES256
35363965613432663466363331356132643130633764653230353265313032316530303638663036
6366316337633530636638333132336138303737353234640a653839353338643762636136333931
62393364653663373634643330336136656634616366343035393331326262346330313638666430
3233656664326133340a613735613464666634393630323335633637643537326235613132636639
66353436633433613364396636613665393936356135613632633465663466666435616531663461
34333235336433653665303334646165333332333334616335376434393931343337383866376161
39353966393765373864333562323733333266646638663664373433343363356534653434306630
32313962363732623239386439623566373765656439653832393261626236393232313765623662
6432
